-- Migration 012: Extraction Quality Fixes
-- Addresses: Single Issue Problem, RCW Dimension, Outcome Standardization, Winner Role Validation
-- Date: 2025-12-19

-- =============================================================================
-- 1. CREATE RCW DIMENSION TABLE
-- =============================================================================
-- Purpose: Normalize RCW references so we can roll up by statute
-- Pattern: Similar to statutes_dim but specific to RCW structure

CREATE TABLE IF NOT EXISTS rcw_dim (
    rcw_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Parsed RCW components for rollup
    title VARCHAR(10) NOT NULL,           -- e.g., "9", "42", "70"
    chapter VARCHAR(10),                   -- e.g., "94A", "56", "44"  
    section VARCHAR(20),                   -- e.g., "525", "010", "200"
    subsection VARCHAR(50),                -- e.g., "(1)", "(1)(a)", "(2)(b)(i)"
    -- Display text
    full_citation CITEXT NOT NULL UNIQUE,  -- e.g., "RCW 9.94A.525(1)"
    display_text CITEXT,                   -- e.g., "Offender Score Calculation"
    -- Metadata
    created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Index for rollup queries
CREATE INDEX IF NOT EXISTS idx_rcw_dim_title ON rcw_dim(title);
CREATE INDEX IF NOT EXISTS idx_rcw_dim_chapter ON rcw_dim(title, chapter);
CREATE INDEX IF NOT EXISTS idx_rcw_dim_section ON rcw_dim(title, chapter, section);

-- =============================================================================
-- 2. CREATE ISSUE-RCW JUNCTION TABLE
-- =============================================================================
-- Purpose: Many-to-many relationship between issues and RCWs
-- An issue can cite multiple RCWs, and an RCW can be cited by multiple issues

CREATE TABLE IF NOT EXISTS issue_rcw (
    issue_id BIGINT NOT NULL REFERENCES issues_decisions(issue_id) ON DELETE CASCADE,
    rcw_id BIGINT NOT NULL REFERENCES rcw_dim(rcw_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (issue_id, rcw_id)
);

-- Index for reverse lookups (find all issues citing an RCW)
CREATE INDEX IF NOT EXISTS idx_issue_rcw_rcw ON issue_rcw(rcw_id);

-- =============================================================================
-- 3. STANDARDIZE ISSUE_OUTCOME TO 5 VALUES
-- =============================================================================
-- Valid values: Affirmed, Dismissed, Reversed, Remanded, Mixed

-- First, normalize existing data
UPDATE issues_decisions SET issue_outcome = 
    CASE 
        WHEN issue_outcome ILIKE '%affirmed in part%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%reversed in part%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%affirmed%' AND issue_outcome ILIKE '%reversed%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%affirmed%' AND issue_outcome ILIKE '%remanded%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%reversed%' AND issue_outcome ILIKE '%remanded%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%partial%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%split%' THEN 'Mixed'
        WHEN issue_outcome ILIKE '%affirm%' THEN 'Affirmed'
        WHEN issue_outcome ILIKE '%dismiss%' THEN 'Dismissed'
        WHEN issue_outcome ILIKE '%revers%' THEN 'Reversed'
        WHEN issue_outcome ILIKE '%remand%' THEN 'Remanded'
        WHEN issue_outcome ILIKE '%mixed%' THEN 'Mixed'
        ELSE issue_outcome  -- Keep as-is if doesn't match patterns
    END
WHERE issue_outcome IS NOT NULL;

-- Add check constraint to enforce 5 valid values
ALTER TABLE issues_decisions DROP CONSTRAINT IF EXISTS chk_issue_outcome;
ALTER TABLE issues_decisions ADD CONSTRAINT chk_issue_outcome
    CHECK (issue_outcome IS NULL OR issue_outcome IN ('Affirmed', 'Dismissed', 'Reversed', 'Remanded', 'Mixed'));

-- =============================================================================
-- 4. VALIDATE WINNER_LEGAL_ROLE (prevent outcome values)
-- =============================================================================
-- Valid values: Appellant, Respondent, Petitioner, Plaintiff, Defendant, State, Neither, null
-- Invalid values: Affirmed, Reversed, etc. (these are outcomes, not roles)

-- First, clean up existing bad data
UPDATE issues_decisions SET winner_legal_role = NULL
WHERE winner_legal_role IN ('Affirmed', 'Reversed', 'Remanded', 'Dismissed', 'Mixed', 
                            'affirmed', 'reversed', 'remanded', 'dismissed', 'mixed');

-- Add check constraint to prevent outcome values in winner_legal_role
ALTER TABLE issues_decisions DROP CONSTRAINT IF EXISTS chk_winner_legal_role;
ALTER TABLE issues_decisions ADD CONSTRAINT chk_winner_legal_role
    CHECK (winner_legal_role IS NULL OR winner_legal_role NOT IN 
           ('Affirmed', 'Reversed', 'Remanded', 'Dismissed', 'Mixed',
            'affirmed', 'reversed', 'remanded', 'dismissed', 'mixed'));

-- =============================================================================
-- 5. ADD ISSUE COUNT TRACKING TO CASES
-- =============================================================================
-- Purpose: Track how many issues each case has for QA purposes

ALTER TABLE cases ADD COLUMN IF NOT EXISTS issue_count INTEGER DEFAULT 0;

-- Update existing cases with actual counts
UPDATE cases c SET issue_count = (
    SELECT COUNT(*) FROM issues_decisions id WHERE id.case_id = c.case_id
);

-- Create trigger to keep issue_count updated
CREATE OR REPLACE FUNCTION update_case_issue_count() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE cases SET issue_count = issue_count + 1 WHERE case_id = NEW.case_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE cases SET issue_count = issue_count - 1 WHERE case_id = OLD.case_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_issue_count ON issues_decisions;
CREATE TRIGGER trg_update_issue_count
    AFTER INSERT OR DELETE ON issues_decisions
    FOR EACH ROW EXECUTE FUNCTION update_case_issue_count();

-- =============================================================================
-- 6. CREATE QA VIEW FOR EXTRACTION VERIFICATION
-- =============================================================================
-- Purpose: Easy comparison with Excel standard for quality assurance

CREATE OR REPLACE VIEW v_qa_extraction AS
SELECT 
    c.case_id,
    c.docket_number,
    c.title AS case_title,
    c.court_level,
    c.court,
    c.county,
    c.appeal_outcome AS overall_outcome,
    c.issue_count,
    c.decision_year,
    c.decision_month,
    -- Issues aggregated
    (SELECT json_agg(json_build_object(
        'issue_id', id.issue_id,
        'summary', LEFT(id.issue_summary, 200),
        'outcome', id.issue_outcome,
        'winner', id.winner_legal_role,
        'taxonomy_id', id.taxonomy_id
    ))
    FROM issues_decisions id
    WHERE id.case_id = c.case_id) AS issues,
    -- Party count
    (SELECT COUNT(*) FROM parties p WHERE p.case_id = c.case_id) AS party_count,
    -- Judge count
    (SELECT COUNT(*) FROM case_judges cj WHERE cj.case_id = c.case_id) AS judge_count,
    -- RCW count (when populated)
    (SELECT COUNT(DISTINCT ir.rcw_id) 
     FROM issue_rcw ir 
     JOIN issues_decisions id ON ir.issue_id = id.issue_id 
     WHERE id.case_id = c.case_id) AS rcw_count,
    c.source_file,
    c.extraction_timestamp
FROM cases c
ORDER BY c.case_id DESC;

COMMENT ON VIEW v_qa_extraction IS 'Quality Assurance view for extraction verification against Excel standard';

-- =============================================================================
-- DONE
-- =============================================================================
